name: Deploy Node Docker App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}

          script: |

            echo "Updating system packages"
            sudo dnf update -y

            echo "Installing git if missing"
            if ! command -v git &> /dev/null
            then
              sudo dnf install git -y
            fi

            echo "Installing docker if missing"
            if ! command -v docker &> /dev/null
            then
              sudo dnf install docker -y
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ec2-user
            fi

            echo "Installing docker-compose if missing"
            if ! command -v docker-compose &> /dev/null
            then
              sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
              -o /usr/local/bin/docker-compose

              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Cloning repo if not exists"
            if [ ! -d "backend-docker" ]; then
              git clone https://github.com/virugamacoder/backend-docker.git
            fi

            cd backend-docker

            echo "Pull latest code"
            git pull origin main

            echo "Stopping old containers"
            docker-compose down || true

            echo "Building and starting containers"
            docker-compose up -d --build

            echo "Deployment completed"