name: Docker Build Push Deploy Zero Downtime

on:
  push:
    branches:
      - main

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-api:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/node-api:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/node-api:buildcache,mode=max


  deploy:

    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            echo "===== Production Zero-Downtime Deploy ====="

            echo "Ensure Docker running"
            sudo dnf install docker -y || true
            sudo systemctl start docker
            sudo systemctl enable docker

            echo "Pull latest image"
            docker pull ${{ secrets.DOCKER_USERNAME }}/node-api:latest

            echo "Detect running container..."

            ACTIVE_PORT=$(docker ps --format '{{.Ports}}' | grep -oE '0\.0\.0\.0:(3000|3001)' | cut -d: -f2)

            if [ "$ACTIVE_PORT" = "3000" ]; then
                NEW_PORT=3001
            elif [ "$ACTIVE_PORT" = "3001" ]; then
                NEW_PORT=3000
            else
                echo "First deployment"
                NEW_PORT=3000
            fi

            echo "Active Port: $ACTIVE_PORT"
            echo "New Port: $NEW_PORT"

            echo "Starting new container..."

            docker run -d \
            -p $NEW_PORT:3000 \
            --name node-api-$NEW_PORT \
            --restart always \
            ${{ secrets.DOCKER_USERNAME }}/node-api:latest

            if [ $? -ne 0 ]; then
                echo "Container start failed"
                exit 1
            fi

            echo "Waiting for container..."
            sleep 6

            echo "Running health check..."

            curl -f http://localhost:$NEW_PORT

            if [ $? -ne 0 ]; then
                echo "Health check failed → rollback"

                docker stop node-api-$NEW_PORT
                docker rm node-api-$NEW_PORT

                exit 1
            fi

            echo "Health check passed"

            echo "Switching Nginx traffic..."

            sudo sed -i "s/localhost:[0-9]*/localhost:$NEW_PORT/" /etc/nginx/conf.d/node-api.conf

            sudo nginx -t
            sudo systemctl reload nginx

            echo "Stopping old container..."

            if [ ! -z "$ACTIVE_PORT" ]; then
                docker stop node-api-$ACTIVE_PORT || true
                docker rm node-api-$ACTIVE_PORT || true
            fi

            echo "Deployment successful"